# Default values for todoapp.

replicaCount: 1

image:
  repository: myrepo/todoapp
  pullPolicy: IfNotPresent
  tag: "1.0"

imagePullSecrets: []

namespace: todoapp
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

serviceAccountName: todo-sa

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity:
  key: kubernetes.io/hostname
  values:
    - kind-worker

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0

pv:
  capacity: 1Gi

pvc:
  storage: 500Mi

secrets:
  - name: DB_USER
    value: todo_user
  - name: DB_PASS
    value: s3cr3t
