kind: ServiceAccount
apiVersion: v1
metadata:
  name: secrets-reader
  namespace: mateapp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mateapp
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secret"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-reader-binding
  namespace: mateapp
subjects:
- kind: ServiceAccount
  name: secrets-reader
roleRef:
  kind: Role
  name: secrets-reader
  apiGroup: rbac.authorization.k8s.io