name: validate-helm

run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  pull_request:
    branches: ["main"]

jobs:
  validate-helm:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Helm tool installer
      uses: Azure/setup-helm@v4.2.0

    - name: output.log is present
      run: |
        if [ ! -f output.log ]; then
          echo "output.log is not present"
          exit 1
        fi

    - name: MYSQL Dependency Present
      if: always()
      run: |
        if ! grep -q "name: mysql" .infrastructure/helm-chart/todoapp/Chart.yaml; then
          echo "MYSQL dependency is not present"
          echo "Inside the Chart.yaml file of todoapp chart, add lines
          ```
          dependencies:
          - name: mysql
          ```"
          exit 1
        fi

    - name: Todoapp Chart Present
      if: always()
      run: |
        if [ ! -d .infrastructure/helm-chart/todoapp ]; then
          echo "Todoapp Chart is not present or named incorrectly"
          exit 1
        fi

    - name: Helm Lint
      if: always()
      run: |
        helm lint .infrastructure/helm-chart/todoapp

    - name: Helm Template
      if: always()
      run: |
        helm template .infrastructure/helm-chart/todoapp -f .infrastructure/helm-chart/todoapp/values.yaml

    - name: MYSQL Chart Present
      if: always()
      run: |
        if [ ! -d .infrastructure/helm-chart/mysql ]; then
          echo "MYSQL Chart is not present or named incorrectly"
          exit 1
        fi

