name: validate-helm

run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  pull_request:
    branches: ["main"]

jobs:
  validate-helm:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Helm tool installer
      uses: Azure/setup-helm@v4.2.0

    - name: Helm Lint
      run: |
        helm lint .infrastructure/helm-chart/todoapp

    - name: Helm Template
      run: |
        helm template .infrastructure/helm-chart/todoapp -f .infrastructure/helm-chart/todoapp/values.yaml
